import Head from "next/head";
import Image from "next/image";
import Header from "../components/global/Header/Header";
import LatestPosts from "../components/global/LatestPosts/LatestPosts";
import LatestVideos from "../components/global/LatestVideos/LatestVideos";
import Logos from "../components/global/logos/Logos";
import { fetchPostsSmall, fetchVideos } from "../utils/fetchPosts";
import styles from "./index.module.css";

export default function Home({ posts, videos }) {
 
  return (
    <div className={styles.home_bg}>
      <Head>
        <title>Calvin Torra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section>
        <div className={styles.hero_box}>
          <div className={styles.hero_title}>
            Revenue Generating Fullstack <br />
            {"&"} Web3 Development
          </div>
          <div className={styles.hero_sub}>
            Increasing revenue and reducing costs are my primary goals. Once
            we've solved those problems, we can then focus on beauty.
          </div>
        </div>
        <Logos />
      </section>
      <section className={styles.gradient_container}>
        <div className={styles.post_container}>
          <LatestPosts posts={posts} />
          <p className={styles.view_more_link}>View More posts ⟿</p>
        </div>
        <div className={styles.gradient_bg_left}></div>
      </section>
      <section className={styles.gradient_container}>
        <div className={styles.post_container}>
          <LatestVideos videos={videos} />
          <p className={styles.view_more_link}>View More Videos ⟿</p>
        </div>
        <div className={styles.gradient_bg_right}></div>
        <div className={styles.footer}></div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await fetchPostsSmall();
  const videos = await fetchVideos();

  return {
    props: { posts: posts, videos: videos },
    revalidate: 1,
  };
}
