import Head from "next/head";
import Image from "next/image";
import LatestPosts from "../components/global/LatestPosts/LatestPosts";
import styles from "./index.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.home_bg}>
      <Head>
        <title>Calvin Torra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className={styles.hero_box}>
          <div className={styles.hero_title}>
            Revenue Generating Fullstack Development
          </div>
          <div className={styles.hero_sub}>
            Increasing revenue and reducing costs are my primary goals. Once
            I've solved those problems, then we can focus on beauty.
          </div>
        </div>
      </section>
      <section>
        <div className={styles.post_container}>
          <LatestPosts posts={posts} />
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await fetch(
    `https://calvint1.sg-host.com/wp-json/wp/v2/react_blog?per_page=100`
  ).then((response) => response.json());

  return {
    props: { posts: posts },
    revalidate: 1,
  };
}
